### ISSUE TITLE
True north calibration and world orientation

### ISSUE THREAD

**Issue by cafedeichi** [ashislaha/Route-Direction-in-AR#1]
Hi, 
Seems like the route directions are not accurate unless I make my iPhone point to the north before opening ARView. I’d like you to let me know if you have already any solutions.

**Comment by ashislaha** [comment]
Is it? But it should work. There are 3 options while AR Co-ordinate system drawing:
Currently I am using the following  worldAlignment: 
    
   let configuration = ARWorldTrackingConfiguration()
   configuration.worldAlignment = .gravityAndHeading // heading (w.r.t. True North) 
   
Other 2 options are : 
  .gravity (heading to the direction where camera opens) and .camera (always to camera view).
